name: CI

on: [push]

jobs: 
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with: 
        java-version: 11
    - name: Build with Maven
      run: mvn compile
    - name: Perform unit testing
      run: mvn test
    - name: Upload coverage report
      with:
        CODECOV_TOKEN: ${{ CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash) 
